name: cl-check.yml
on:
  workflow_dispatch:

jobs:
  build:
    name: Check
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: setup cl
        run: call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        shell: cmd
        
      - name: cl-check
        run: cl
        shell: cmd

      
