name: release-native.yml
on:
  workflow_dispatch:

jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # for release
    env:
      MAVEN_ARGS: --batch-mode --no-transfer-progress
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4

      # - uses: graalvm/setup-graalvm@v1
      #   with:
      #     java-version: '21'
      #     distribution: 'graalvm'
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     native-image-job-reports: 'true'
      #     cache: 'maven'
        
      # - name: Process aot
      #   run: mvn  compile spring-boot:process-aot

#      - name: Build native app
#        run: |
#            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
#            mvn  gluonfx:build
#        shell: cmd

      - name: Create a folder
        run: mkdir -p target/gluonfx/x86_64-windows

      - name: Create a file
        run: date >  target/gluonfx/x86_64-windows/spring-boot-java-fx.exe

      - name: Verify .exe file exists
        run: |
          ls -l target/gluonfx/x86_64-windows/
          test -f target/gluonfx/x86_64-windows/spring-boot-java-fx.exe

      - name: Upload
        run: |
          gh release delete my-release --yes
          git tag -f my-release-tag
          git push origin -f my-release-tag
          gh release create my-release
          gh release upload my-release target/gluonfx/x86_64-windows/spring-boot-java-fx.exe --clobber
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}


      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     tag: poletto
      #     file: target/gluonfx/x86_64-windows/spring-boot-java-fx.exe
      #     overwrite: true
      #     make_latest: true
