name: release-native.yml
on:
  workflow_dispatch:

jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # for release
    env:
      MAVEN_ARGS: --batch-mode --no-transfer-progress
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: 'maven'
        
      - name: Process aot
        run: mvn  compile spring-boot:process-aot

#      - name: Build native app
#        run: |
#            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
#            mvn --batch-mode --no-transfer-progress gluonfx:build
#        shell: cmd

      - name: Create a file
        run: touch target/gluonfx/x86_64-windows/spring-boot-java-fx.exe


      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          release_name: native-image
          file: target/gluonfx/x86_64-windows/spring-boot-java-fx.exe
          overwrite: true
          make_latest: true
